import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useApp } from '../context/AppContext';
import { generateMunicipalPDFReport } from '../utils/pdfGenerator';
import { CategoryBadge } from '../components/CategoryBadge';
import {
  FileBarChart,
  Download,
  Calendar,
  Building2,
  FileText,
  CheckCircle2,
  Clock,
  AlertOctagon,
  Printer,
  Sparkles,
} from 'lucide-react';

export const AnalyticsReportsPage: React.FC = () => {
  const { currentUser } = useAuth();
  const { complaints, hotspots, stats } = useApp();

  const [period, setPeriod] = useState<'Daily' | 'Weekly' | 'Monthly' | 'All-Time'>('Monthly');
  const [isExporting, setIsExporting] = useState(false);

  const handleExportPDF = () => {
    setIsExporting(true);
    setTimeout(() => {
      generateMunicipalPDFReport({
        reportType: period,
        complaints,
        hotspots,
        stats,
        generatedBy: currentUser?.fullName || 'Municipal Administrator',
      });
      setIsExporting(false);
    }, 400);
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-[#22223B] text-white p-6 sm:p-8 rounded-3xl border border-[#4A4E69] shadow-lg flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold uppercase tracking-wider text-[#C9ADA7] bg-[#4A4E69]/40 px-3 py-1 rounded-full border border-[#9A8C98]/30">
              Official Municipal Audit Suite
            </span>
            <span className="text-xs text-stone-300">Sangamner Municipal Corporation</span>
          </div>
          <h2 className="font-heading text-2xl sm:text-3xl font-extrabold text-white">
            Analytics & PDF Export Portal
          </h2>
          <p className="text-stone-300 text-xs sm:text-sm">
            Generate verifiable PDF audit reports containing complaint timelines, category breakdowns, and Frequent Dumping Zone records.
          </p>
        </div>

        <button
          onClick={handleExportPDF}
          disabled={isExporting}
          className="bg-[#C9ADA7] hover:bg-[#bba099] text-[#22223B] font-bold px-6 py-3.5 rounded-2xl text-xs sm:text-sm flex items-center gap-2 shadow-xl transition-all shrink-0"
        >
          <Printer className="w-4 h-4 text-[#22223B]" />
          <span>{isExporting ? 'Generating PDF...' : `Export ${period} Audit PDF`}</span>
        </button>
      </div>

      {/* Audit Period Selector */}
      <div className="bg-white p-6 rounded-3xl border border-[#9A8C98]/20 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <Calendar className="w-5 h-5 text-[#22223B]" />
          <div>
            <h3 className="font-heading text-sm font-bold text-[#22223B]">Select Audit Period</h3>
            <p className="text-xs text-[#4A4E69]">Filter complaint data for report compilation</p>
          </div>
        </div>

        <div className="flex items-center gap-2 bg-stone-100 p-1.5 rounded-2xl border border-stone-200">
          {(['Daily', 'Weekly', 'Monthly', 'All-Time'] as const).map((p) => (
            <button
              key={p}
              onClick={() => setPeriod(p)}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                period === p
                  ? 'bg-[#22223B] text-white shadow'
                  : 'text-[#4A4E69] hover:bg-stone-200'
              }`}
            >
              {p}
            </button>
          ))}
        </div>
      </div>

      {/* PDF Report Live Preview Component */}
      <div className="bg-white p-8 rounded-3xl border-2 border-stone-200 shadow-md space-y-6 max-w-4xl mx-auto">
        {/* PDF Header Mockup */}
        <div className="bg-[#22223B] text-white p-6 rounded-2xl space-y-2">
          <div className="flex justify-between items-start">
            <div>
              <h3 className="font-logo text-xl font-bold text-[#C9ADA7]">
                WASTEWATCH MUNICIPAL AUDIT
              </h3>
              <p className="text-xs text-stone-300">
                Sangamner Municipal Authority & Amrutvahini College of Engineering
              </p>
            </div>
            <span className="text-xs bg-[#4A4E69] text-white px-3 py-1 rounded-full font-mono font-bold">
              {period} Audit
            </span>
          </div>
          <div className="text-[10px] text-stone-300 pt-2 border-t border-[#4A4E69]/60 flex justify-between">
            <span>Generated By: {currentUser?.fullName || 'Municipal Admin'}</span>
            <span>Date: {new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}</span>
          </div>
        </div>

        {/* Summary Numbers */}
        <div className="grid grid-cols-4 gap-4 text-center">
          <div className="p-4 bg-[#F2E9E4] rounded-2xl border border-[#9A8C98]/20">
            <div className="text-2xl font-bold text-[#22223B]">{stats.totalComplaints}</div>
            <div className="text-[11px] font-semibold text-[#4A4E69]">Total Logged</div>
          </div>
          <div className="p-4 bg-amber-50 rounded-2xl border border-amber-200">
            <div className="text-2xl font-bold text-amber-900">{stats.pendingCount}</div>
            <div className="text-[11px] font-semibold text-amber-800">Pending</div>
          </div>
          <div className="p-4 bg-emerald-50 rounded-2xl border border-emerald-200">
            <div className="text-2xl font-bold text-emerald-900">{stats.resolvedCount}</div>
            <div className="text-[11px] font-semibold text-emerald-800">Resolved</div>
          </div>
          <div className="p-4 bg-rose-50 rounded-2xl border border-rose-200">
            <div className="text-2xl font-bold text-rose-900">{stats.activeHotspots}</div>
            <div className="text-[11px] font-semibold text-rose-800">Hotspots</div>
          </div>
        </div>

        {/* Table Mockup Preview */}
        <div className="space-y-3">
          <h4 className="font-heading text-xs font-bold text-[#22223B] uppercase tracking-wider">
            Complaints Log Preview ({complaints.length} Records)
          </h4>

          <div className="border border-stone-200 rounded-2xl overflow-hidden text-xs">
            <table className="w-full text-left">
              <thead className="bg-[#22223B] text-white text-[11px]">
                <tr>
                  <th className="p-3">ID</th>
                  <th className="p-3">Category</th>
                  <th className="p-3">Location</th>
                  <th className="p-3">Status</th>
                  <th className="p-3">Date</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-stone-100 font-medium text-[#22223B]">
                {complaints.slice(0, 5).map((c) => (
                  <tr key={c.id} className="hover:bg-stone-50">
                    <td className="p-3 font-mono font-bold">#{c.id}</td>
                    <td className="p-3">{c.category}</td>
                    <td className="p-3 truncate max-w-[200px]">{c.locationName}</td>
                    <td className="p-3 font-bold">{c.status}</td>
                    <td className="p-3 text-stone-500">{new Date(c.createdAt).toLocaleDateString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="pt-4 flex justify-end">
          <button
            onClick={handleExportPDF}
            className="px-8 py-3 bg-[#22223B] hover:bg-[#333355] text-white font-bold text-xs rounded-2xl shadow-lg flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            <span>Download Official PDF File</span>
          </button>
        </div>
      </div>
    </div>
  );
};
