import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Complaint, Hotspot, SystemStats } from '../types';

export interface PDFReportOptions {
  reportType: 'Daily' | 'Weekly' | 'Monthly' | 'All-Time';
  complaints: Complaint[];
  hotspots: Hotspot[];
  stats: SystemStats;
  generatedBy: string;
}

export function generateMunicipalPDFReport(options: PDFReportOptions) {
  const doc = new jsPDF();
  const { reportType, complaints, hotspots, stats, generatedBy } = options;

  // Header Colors (Municipal Theme: Primary #22223B, Secondary #4A4E69)
  const primaryColor = [34, 34, 59]; // #22223B
  const secondaryColor = [74, 78, 105]; // #4A4E69

  // Header Banner
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 32, 'F');

  // Title Text
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('WASTEWATCH - MUNICIPAL REPORT', 14, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('Illegal Dumping Monitoring System | Amrutvahini College of Engineering', 14, 26);

  // Report Metadata Box
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Report Period: ${reportType} Audit`, 14, 42);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated On: ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })} at ${new Date().toLocaleTimeString()}`, 14, 48);
  doc.text(`Generated By: ${generatedBy}`, 14, 54);

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 58, 196, 58);

  // Executive Summary Cards
  doc.setFillColor(242, 233, 228); // #F2E9E4
  doc.roundedRect(14, 62, 42, 22, 2, 2, 'F');
  doc.roundedRect(60, 62, 42, 22, 2, 2, 'F');
  doc.roundedRect(106, 62, 42, 22, 2, 2, 'F');
  doc.roundedRect(152, 62, 44, 22, 2, 2, 'F');

  doc.setFontSize(9);
  doc.setTextColor(74, 78, 105);
  doc.text('Total Complaints', 18, 68);
  doc.text('Pending Action', 64, 68);
  doc.text('Resolved Cases', 110, 68);
  doc.text('Active Hotspots', 156, 68);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(34, 34, 59);
  doc.text(String(stats.totalComplaints), 18, 78);
  doc.text(String(stats.pendingCount), 64, 78);
  doc.text(String(stats.resolvedCount), 110, 78);
  doc.text(String(stats.activeHotspots), 156, 78);

  // Complaints Table Title
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Complaints Log Detail', 14, 94);

  // AutoTable for Complaints
  const tableData = complaints.map((c) => [
    c.id.substring(0, 8),
    new Date(c.createdAt).toLocaleDateString('en-IN'),
    c.category,
    c.locationName || `${c.latitude.toFixed(3)}, ${c.longitude.toFixed(3)}`,
    c.status,
    c.reporterName || 'Anonymous'
  ]);

  autoTable(doc, {
    startY: 98,
    head: [['ID', 'Date', 'Category', 'Location', 'Status', 'Reporter']],
    body: tableData,
    headStyles: {
      fillColor: [34, 34, 59],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [248, 245, 242]
    },
    styles: {
      fontSize: 8,
      cellPadding: 3
    }
  });

  // Hotspots Summary Section if present
  let currentY = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY + 12 : 180;

  if (currentY > 240) {
    doc.addPage();
    currentY = 20;
  }

  if (hotspots.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 34, 59);
    doc.text('Frequent Dumping Zones (Hotspot Clusters)', 14, currentY);

    const hotspotData = hotspots.map((h) => [
      h.id,
      h.locationName,
      `${h.complaintCount} Reports`,
      h.primaryCategory,
      h.status
    ]);

    autoTable(doc, {
      startY: currentY + 4,
      head: [['Zone ID', 'Location Centroid', 'Cluster Size', 'Dominant Category', 'Status']],
      body: hotspotData,
      headStyles: {
        fillColor: [74, 78, 105],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      styles: {
        fontSize: 8,
        cellPadding: 3
      }
    });

    currentY = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY + 20 : currentY + 40;
  } else {
    currentY += 10;
  }

  if (currentY > 250) {
    doc.addPage();
    currentY = 20;
  }

  // Official Signature Block
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Official Verification Signature & Stamp:', 14, currentY + 10);
  doc.line(14, currentY + 30, 90, currentY + 30);
  doc.text('Municipal Sanitary Inspector / Administrator', 14, currentY + 35);

  doc.line(120, currentY + 30, 196, currentY + 30);
  doc.text('Sangamner Municipal Council Seal', 120, currentY + 35);

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount} | Confidential Municipal Document - WasteWatch`, 105, 290, { align: 'center' });
  }

  // Trigger Save
  const fileName = `WasteWatch_Audit_${reportType}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}
